### ISSUE TITLE
Example?

### ISSUE THREAD

**Issue by nuthinking** [Yahweasel/mkvdemuxjs#1]
How can you convert the `MediaRecorder` into video frames?

**Comment by Yahweasel** [comment]
MediaRecorder creates blobs IIRC, so you'd have to convert them into ArrayBuffers, then just `push` them into the library and `demux`. See test.js.

That being said, this library is no longer maintained. I'll be archiving it immediately after posting this, as it's creating some confusion. I use libav.js for everything this library provided.
